-- env.template.lua — committed template documenting per-machine Neovim config.
--
-- USAGE:
--   1. Copy this file to env.lua (sibling of init.lua, gitignored):
--        cp env.template.lua env.lua
--   2. Edit env.lua and set the values appropriate for your machine.
--   3. env.lua is loaded by init.lua via `pcall(dofile, ...)` at startup.
--
-- DO NOT EDIT THIS FILE for personal settings — edit env.lua instead.
-- This file should only be updated to document new variables that env.lua may set.

-- Path to your personal todo file, opened by <leader>ko (checkmate.nvim).
vim.g.todo_file = vim.fn.expand('~/Development/todo.md')

-- Path to your personal notes directory. When set, Neo-tree gains a
-- "notes" source tab and <leader>n toggles the sidebar to it. If unset,
-- <leader>n shows a notify and does nothing.
-- vim.g.notes_dir = vim.fn.expand('~/Development/notes')
